### ISSUE TITLE
No such file or directory: 'hhsearch': 'hhsearch'

### ISSUE THREAD

**Issue by swallow-design** [delalamo/af2_conformations#8]
hello,When I run the code, I encountered the following problem：
* Connection #0 to host a3m-templates.mmseqs.com left intact
Traceback (most recent call last):
  File "/data/alphafold2/run_af2_con.py", line 28, in <module>
    max_recycles = 1, n_struct_module_repeats = 8 )
  File "/data/alphafold2/af2_conformations/scripts/predict.py", line 199, in predict_structure_from_templates
    seq, a3m_lines, util.mk_template(seq, a3m_lines, template_path).features
  File "/data/alphafold2/af2_conformations/scripts/util.py", line 70, in mk_template
    ).query(a3m_lines)
  File "/data/alphafold2/alphafold/data/tools/hhsearch.py", line 87, in query
    cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/root/anaconda3/envs/alphafold/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/root/anaconda3/envs/alphafold/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hhsearch': 'hhsearch'
I installed the Dockers version of Alphafold2. Whether I need a non -docker version Alpahfold to use af2_conformations

**Comment by swallow-design** [comment]
After using the non -docker version of Alphafold2 to run code, why is the out.pdb files empty.During the operation, there is no error.

**Comment by delalamo** [comment]
You might not have hh-suite in your path. I believe this is automatically set by docker
